name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  # UI & Icons
  cached_network_image: ^3.4.1        # Thay cho Coil
  cupertino_icons: ^1.0.9
  dio: ^5.9.2
  drift: ^2.32.1                      # Type-safe database
  equatable: ^2.0.8                   # So sánh Object (rất quan trọng cho BLoC)
  fl_chart: ^1.2.0                    # Thay cho MPAndroidChart
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_spinkit: ^5.2.2             # Animation loading

  # State Management & Logic
  get_it: ^9.2.1                      # Dependency Injection (Thay cho Hilt)
  go_router: ^17.1.0                  # Thay cho Navigation Compose
  injectable: ^2.7.1+4                # Annotation cho GetIt
  intl: ^0.20.2                       # Format tiền tệ, ngày tháng
  json_annotation: ^4.11.0
  path: ^1.9.1

  # Local Database (Thay cho Room)
  path_provider: ^2.1.5
  retrofit: ^4.9.2                    # Networking & API (Thay cho Retrofit/OkHttp)
  sqlite3_flutter_libs: ^0.6.0+eol
  uuid: ^4.5.3

dev_dependencies:
  build_runner: ^2.13.1               # Tool chạy code generation
  drift_dev: ^2.32.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.12.1
  json_serializable: ^6.13.1
  retrofit_generator: ^10.2.3

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf